### ISSUE TITLE
スマホ表示で、youtubeの埋め込みが右にはみ出ている

### ISSUE THREAD

**Issue by ghost** [imateka/test_r#2]
## 概要
スマホ表示で、youtubeの埋め込みが右にはみ出ている
![2017-04-15 11 18 39](https://cloud.githubusercontent.com/assets/26996674/25060023/9284e544-21cd-11e7-8e11-5ecee74b7ecb.png)

## 期待する挙動・表示（バグの場合）
ニコニコ動画と同じく、右にはみ出ずエリア内におさまって表示される

## 対象
[「音楽」ページ](http://imateka.net/%E9%9F%B3%E6%A5%BD/)内に埋め込まれたyoutube

## 備考
記事内に埋め込まれうる他のものについても対応した方がいいかも

**Comment by imateka** [comment]
とりあえず、画像は漫画とプラグイン入れたやつはちょうどハマってるぽい

**Comment by wmsnagano** [comment]
2017/04/28リリース済のためクローズ

**Comment by ghost** [comment]
@imateka 
2017/04/28リリース済
問題なければIssueクローズお願いします！

**Comment by imateka** [comment]
2017/04/28
固定ページ：音楽にてyoutube動画のはみ出し修正確認しました。
クローズします。
