### ISSUE TITLE
スマホ表示で、ヘッダー内のテキストの左右がディスプレイにくっついている

### ISSUE THREAD

**Issue by ghost** [imateka/test_r#4]
## 概要
スマホ表示で、ヘッダー内のテキストの左右がディスプレイにくっついている
![2017-04-15 11 37 34](https://cloud.githubusercontent.com/assets/26996674/25060110/4ccd362a-21d0-11e7-91e7-ac4f0824ca04.png)

## 期待する挙動・表示（バグの場合）
メインエリアと同じ値、左右余白をとる

## 対象
全ページのヘッダー内の
- h1見出し
- h1見出し直下のテキスト

## 備考
- pcとspで同一の左右余白もたせてOKそう

**Comment by ghost** [comment]
@imateka 
2017/04/28リリース済
問題なければIssueクローズお願いします！

**Comment by imateka** [comment]
2017/04/28
見出し文字を増やしても、左右に余白があることを確認しました。
クローズします。
