### ISSUE TITLE
目次として使っているリストに、アイコンとして不要な「▷」が表示される

### ISSUE THREAD

**Issue by ghost** [imateka/test_r#5]
## 概要
目次として使っているリストに、アイコンとして不要な「▷」が表示される
<img width="386" alt="2017-04-18 08 48 42" src="https://cloud.githubusercontent.com/assets/26996674/25108917/2ce49fba-2414-11e7-8e71-f5abb2369eba.png">

## 期待する挙動・表示（バグの場合）
「▷」が表示されない

## 対象
[記事](http://imateka.net/blog/vocaloid1/#more-518)内の目次
クラス「no_bullets」

## 備考
- 記事内のul/olは基本「▷」つける形で実装しているが、絞った指定にした方がいいかも

**Comment by ghost** [comment]
@imateka 
2017/04/28リリース済
問題なければIssueクローズお願いします！

**Comment by imateka** [comment]
2017/04/27
ボーマス関連ページにて矢印が点になっているのを確認しました。
クローズします。
